# Drug Consumption Final Project for COMP 562 - Random Forest Methods
#### by Priyanshi Aeron

## Import Libraries and Data

In [39]:
import pandas as pd
import numpy as np
from sklearn.inspection import permutation_importance
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import datasets
from sklearn import svm
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


drug_labels = ['Alcohol','Amphet','Amyl','Benzos','Caff','Choc','Coke','Crack','Ecstasy','Heroin','Ketamine','Legalh','LSD','Meth','Mushrooms','Nicotine','VSA']
sched_1 = ['Heroin','LSD','Ecstasy','Mushrooms']
sched_2 = ['Amphet','Coke','Crack','Meth']
sched_3 = ['Ketamine']
sched_4 = ['Benzos']
not_controlled_substance = ['Alcohol','Amyl','Caff','Choc','Legalh','Nicotine','VSA']
schedules = ['Sch1','Sch2','Sch3','Sch4', 'SchNA']
personality_labels = ['Nscore','Escore','Oscore','Ascore','Cscore','Impulsive','SS']
demographic_labels = ['Age','Gender','Education','Country','Ethnicity']
target_label = ['Cannabis']

In [41]:
drugs = pd.read_csv('drugs.csv')
print(drugs.shape)
drugs.head()

(1877, 35)


Age  Gender                          Education Country  \
0  35-44       1  Professional certificate/ diploma      UK   
1  25-34       0                   Doctorate degree      UK   
2  35-44       0  Professional certificate/ diploma      UK   
3  18-24       1                     Masters degree      UK   
4  35-44       1                   Doctorate degree      UK   

           Ethnicity  Nscore  Escore  Oscore  Ascore  Cscore  ...  LSD  Meth  \
0  Mixed-White/Asian    39.0    36.0    42.0    37.0    42.0  ...    0     0   
1              White    29.0    52.0    55.0    48.0    41.0  ...    1     1   
2              White    31.0    45.0    40.0    32.0    34.0  ...    0     0   
3              White    34.0    34.0    46.0    47.0    46.0  ...    0     0   
4              White    43.0    28.0    43.0    41.0    50.0  ...    0     0   

   Mushrooms  Nicotine  VSA  Sch1  Sch2 Sch3  Sch4  SchNA  
0          0         1    0     0     1    0     1      1  
1          0         1    0     1     1    1     0      1  
2          1         0    0     1     0    0     0      1  
3          0         1    0     0     1    1     1      1  
4          1         1    0     1     1    0     0      1  

[5 rows x 35 columns]

## Support Vector Machine

In [51]:
drugsC = pd.read_csv('SVMdrugs.csv')
y = drugsC['Cannabis']
X = drugsC.drop(target_label, 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)
svclassifier = SVC(kernel = 'linear')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

[[44  0  0  0  0  0  2]
 [ 8  9  1  0  0  0  2]
 [ 9  3  1  0  0  0  8]
 [ 1  1  2  1  0  0 24]
 [ 1  1  0  1  0  0  7]
 [ 1  0  0  0  0  0 14]
 [ 3  1  3  1  0  0 39]]
              precision    recall  f1-score   support

         CL0       0.66      0.96      0.78        46
         CL1       0.60      0.45      0.51        20
         CL2       0.14      0.05      0.07        21
         CL3       0.33      0.03      0.06        29
         CL4       0.00      0.00      0.00        10
         CL5       0.00      0.00      0.00        15
         CL6       0.41      0.83      0.55        47

    accuracy                           0.50       188
   macro avg       0.31      0.33      0.28       188
weighted avg       0.39      0.50      0.40       188

Accuracy: 0.5


/Users/priyanshiaeron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/priyanshiaeron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/priyanshiaeron/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r

In [50]:
drugsC = pd.read_csv('SVMdrugs.csv')
y = drugsC['Cannabis']
X = drugsC.drop(target_label, 1)
y = np.where((y == 'CL0'), 0, 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)
svclassifier = SVC(kernel = 'linear')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

[[ 27  20]
 [  7 134]]
              precision    recall  f1-score   support

           0       0.79      0.57      0.67        47
           1       0.87      0.95      0.91       141

    accuracy                           0.86       188
   macro avg       0.83      0.76      0.79       188
weighted avg       0.85      0.86      0.85       188

Accuracy: 0.8563829787234043
